### ISSUE TITLE
RX on Nexus 6 failed

### ISSUE THREAD

**Issue by Radiomix2000** [demantz/hackrf_android#11]
Getting the message:
 _Saving samples to /storage/emulated/0/Test_HackRF/hackrf_android.iq
 error (File IO)!_
Tried to change the path, it doesn't work. Entering the path (/sdcard/hackrf_android.iq) in Filename field gives a result in log _Saving samples to /storage/emulated/0/Test_HackRF/sdcard/hackrf_android.iq_

**Comment by Radiomix2000** [comment]
Forgot to mention.
RX to /dev/null works fine.
Seems to be an issue with path to file.
Checked the path _/storage/emulated/0/_
and it looks like incorrect path.
On Nexus 6 is better to get access to file via /sdcard/

**Comment by demantz** [comment]
The error was due to the new permission system of Android. Even though the app Manifest requests storage permissions, they are not granted without explicitly asking the user. Version 1.12 of the HackRF_Test app handles this correctly. Alternatively you can go to (Android-)Settings - Apps - HackRF_Test - Permissions - (turn on the Storage Permission)

Sorry for the late reply, I was busy with exams..
