### ISSUE TITLE
/storage/emulated/0/Test_HackRF/hackrf_android.iq

### ISSUE THREAD

**Issue by clearvision17** [demantz/hackrf_android#12]
/storage/emulated/0/Test_HackRF/hackrf_android.iq

seem to have this error any ideas? would like to change the default location but the settings button does not work

**Comment by Radiomix2000** [comment]
Probably it's the same issue as issue #11 ( https://github.com/demantz/hackrf_android/issues/11 )

**Comment by clearvision17** [comment]
yea but i cannot fix it

**Comment by clearvision17** [comment]
any ideas, where is the developer?

**Comment by SonyKucing** [comment]
please send here complete error message ...

**Comment by clearvision17** [comment]
/storage/emulated/0/Test_HackRF/hackrf_android.iq -  this is the complete error message

**Comment by demantz** [comment]
The error was due to the new permission system of Android. Even though the app Manifest requests storage permissions, they are not granted without explicitly asking the user. Version 1.12 of the HackRF_Test app handles this correctly. Alternatively you can go to (Android-)Settings - Apps - HackRF_Test - Permissions - (turn on the Storage Permission)

Sorry for the late reply, I was busy with exams..

**Comment by Max720027** [comment]
How to change the extension to * .wav?

**Comment by Max720027** [comment]
How to change the extension to * .wav?
